/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jacksploit;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testApp() {
        App app = new App();
    }
}
