Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.network "forwarded_port", guest: 4567, host: 4567

  config.vm.provision :file do |file|
    file.source = "jdk-8-linux-x64.tar.gz"
    file.destination = "/home/vagrant/"
  end

  config.vm.provision "shell", path: "prov.sh", privileged: false
end
